# got from https://github.com/pages-themes/minimal/blob/master/_config.yml

title: Ian Wixom
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true

# got from https://github.com/jekyll/minima/releases

remote_theme: jekyll/minima@v2.5.2
plugins:
  - jekyll-remote-theme
